version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=zyl7758258
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports :
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:zyl7758258@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]
    command: ["/app/main"]