name: deploy to production

on push:
  branches: [ master ]

jobs: 
  build: 
    name: build image
    runs-on: ubuntu-latest
  
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to aliyun
      uses: aliyun/acr-login@v1
      with:
        region-id: cn-hangzhou # example: cn-hangzhou
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"

    - name: Build and push image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/myrepo/demo:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/myrepo/demo:$IMAGE_TAG

